name: ldm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - brotli=1.0.9=h7f98852_5
  - brotli-bin=1.0.9=h7f98852_5
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py38h578d9bd_2
  - cudatoolkit=11.0.221=h6bb024c_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.2.10=h9c3ff4c_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=hf484d3e_1000
  - intel-openmp=2022.0.1=h06a4308_3633
  - jpeg=9d=h7f8727e_0
  - kiwisolver=1.3.2=py38h295c915_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libbrotlicommon=1.0.9=h7f98852_5
  - libbrotlidec=1.0.9=h7f98852_5
  - libbrotlienc=1.0.9=h7f98852_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.1=py38h578d9bd_0
  - matplotlib-base=3.5.1=py38ha18d171_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h7f8727e_2
  - ninja=1.10.2=py38hd09550d_3
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - openssl=1.1.1n=h7f8727e_0
  - packaging=21.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.0.1=py38h22f2fdc_0
  - pip=20.3.3=py38h06a4308_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyqt=5.9.2=py38h05f1152_4
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.7.0=py3.8_cuda11.0.221_cudnn8.0.3_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py38h06a4308_0
  - sip=4.19.13=py38h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchvision=0.8.1=py38_cu110
  - tornado=6.1=py38h497a2fe_1
  - typing_extensions=4.1.1=pyh06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - albumentations==0.4.3
    - altair==4.2.0
    - antlr4-python3-runtime==4.8
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - async-timeout==4.0.2
    - attrs==21.4.0
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.10.0
    - black==22.3.0
    - bleach==4.1.0
    - blinker==1.4
    - cachetools==5.0.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - dataclasses==0.6
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - einops==0.3.0
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - filelock==3.6.0
    - frozenlist==1.3.0
    - fsspec==2022.3.0
    - ftfy==6.1.1
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - idna==3.3
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - imgaug==0.2.6
    - importlib-metadata==4.11.3
    - importlib-resources==5.6.0
    - ipykernel==6.12.1
    - ipython==8.2.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.1.1
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter-client==7.2.1
    - jupyter-core==4.9.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.0
    - lpips==0.1.4
    - markdown==3.3.6
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - multidict==6.0.2
    - mypy-extensions==0.4.3
    - nbclient==0.5.13
    - nbconvert==6.4.5
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - networkx==2.7.1
    - notebook==6.4.10
    - oauthlib==3.2.0
    - omegaconf==2.1.1
    - opencv-python==4.1.2.30
    - opencv-python-headless==4.5.5.64
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.9.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.5.2
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.29
    - protobuf==3.20.0
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pudb==2019.2
    - pure-eval==0.2.2
    - pyarrow==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pydeck==0.7.1
    - pydeprecate==0.3.1
    - pygments==2.11.2
    - pympler==1.0.1
    - pyrsistent==0.18.1
    - pytorch-lightning==1.4.2
    - pytz==2022.1
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==22.3.0
    - regex==2022.3.15
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sacremoses==0.0.49
    - scikit-image==0.19.2
    - scipy==1.8.0
    - semver==2.13.0
    - send2trash==1.8.0
    - smmap==5.0.0
    - soupsieve==2.3.1
    - stack-data==0.2.0
    - streamlit==1.8.1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.13.3
    - test-tube==0.7.5
    - testpath==0.6.0
    - tifffile==2022.3.25
    - tokenizers==0.10.3
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.11.2
    - torch-fidelity==0.3.0
    - torchmetrics==0.7.3
    - tqdm==4.64.0
    - traitlets==5.1.1
    - transformers==4.3.1
    - tzdata==2022.1
    - tzlocal==4.2
    - urllib3==1.26.9
    - urwid==2.1.2
    - validators==0.18.2
    - watchdog==2.1.7
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.1.1
    - widgetsnbextension==3.6.0
    - yarl==1.7.2
    - zipp==3.8.0
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
